# Generated by Django 3.1 on 2023-11-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'verbose_name': 'FAQQuestion', 'verbose_name_plural': 'FAQQuestions'},
        ),
    ]
