# Generated by Django 3.1 on 2023-11-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20231110_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='answer',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
