# Generated by Django 3.1 on 2023-09-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('no_of_employees', models.CharField(choices=[(0, 'Select No of Employees'), ('1-5', '1-5'), ('6-10', '6-10'), ('21-50', '21-50'), ('50-200', '50-200'), ('201-500', '201-500'), ('more than 500', 'More Than 500')], default=0, max_length=15)),
                ('message', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[(0, 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Tictok', 'Tictok'), ('Marketer', 'Marketer'), ('others', 'Others')], default=0, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
