# Generated by Django 3.1 on 2023-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
