# Generated by Django 3.1 on 2023-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20231104_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.CharField(choices=[(0, 'Select How you heard about us'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Google', 'Google'), ('word of mouth', 'Word of Mouth'), ('youtube', 'Youtube'), ('Tiktok', 'Tiktok'), ('Marketer', 'Marketer'), ('others', 'Others')], default=0, max_length=100),
        ),
    ]
