# Generated by Django 3.1 on 2023-11-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('service', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name': 'SubServiceType',
                'verbose_name_plural': 'SubService Types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transactionType', models.CharField(choices=[(0, 'Select Transaction Type'), ('credit', 'credit'), ('debit', 'debit')], default=0, max_length=100)),
                ('user_email', models.EmailField(max_length=50)),
                ('cumulativeOut', models.IntegerField(blank=True, null=True)),
                ('cumulativeIn', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('service', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subServiceType', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='service', chained_model_field='service', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.subservicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('approval_note', models.TextField(max_length=500)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('service', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subServiceType', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='service', chained_model_field='service', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.subservicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('service', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='company', chained_model_field='company', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
                ('subServiceType', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='service', chained_model_field='service', default=None, on_delete=django.db.models.deletion.CASCADE, to='service.subservicetype')),
            ],
        ),
    ]
