# Generated by Django 3.1 on 2023-11-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_prerequisite_subservice_subservicetype_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'SubService', 'verbose_name_plural': 'SubServices'},
        ),
    ]
