# Generated by Django 3.1 on 2023-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20231122_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='approval',
            field=models.CharField(choices=[(0, 'Select Approval'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Pending', max_length=100),
        ),
    ]
