# Generated by Django 3.1 on 2023-11-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_subservice_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='is_pending',
        ),
    ]
