# Generated by Django 3.1 on 2023-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20231130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='char_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
