# Generated by Django 3.1 on 2023-12-18 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20231218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
