# Generated by Django 3.1 on 2023-12-19 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20231219_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='char_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
