# Generated by Django 3.1 on 2023-12-19 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20231219_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='char_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
