# Generated by Django 3.1 on 2023-12-19 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20231219_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='char_id',
            field=models.CharField(blank=True, default=uuid.uuid5, max_length=22, null=True, unique=True),
        ),
    ]
