# Generated by Django 3.1 on 2023-12-20 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20231220_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='char_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=32, null=True, unique=True),
        ),
    ]
