# Generated by Django 3.1 on 2023-12-27 13:28

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_auto_20231227_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='char_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijkmnopqrstuvwxyz1234567890', blank=True, length=13, max_length=22, null=True, prefix='acc_', unique=True),
        ),
    ]
